import React from 'react';
import '../styles/globals.css';
import { NavBar, FooterBar } from './page';



export const metadata = {
  title: 'SAP',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en" data-theme="luxury">
      <body>
        <NavBar/>
        {/* The Divider named 'page-content' is used to create space for the pages content
        and it's child div which holds '{children}' is used to apply the flex grow attribute which allows the View
        Divider to take up all the space that is created */}
        {children}
        {/* <FooterBar/> */}
      </body>
    </html>
  )
}

